### PR TITLE
Async histogram log writer

### PR DESCRIPTION
**Pull request by tebeco**
this PR is preparing work to be able to address #67
I'm probably missing some point here and there :
- [x] remove netcoreapp1.x
- [x] added netstandard2.0
- [x] added netcoreapp2.0
- [x] added netcoreapp2.1
- [x] remove usage of blocking API from `StreamWriter`

As long as a `StreamWriter` is used there's no async method that actually accept a `CancellationToken` so this is not funny ... will see if it is possible to handle it

### CODE REVIEW

**Comment by tebeco** [comment]
@thefringeninja 
do you want a second pass on it to be sure it's up to date ?
especially the TFM ?

**Comment by tebeco** [comment]
it could be in another PR

i would probably drop netcoreapp2.x in the sample in favor for 3.1 (as this is the current LTS)

**Comment by thefringeninja** [comment]
This PR is newer then the last change to the repo so it's probably ok?

**Comment by tebeco** [comment]
i did not checked, that's why i'm asking but when i see i use nc2.0 and 2.1
either you can merge it and will do a new bump
or i can try to check this ^^ i don't mind either

also i would love a triple check to be sure i did not destroyed some idea or perf when adding an async path to the lib
my expertise is the way the lib works and is polished are probably limited ^^

The "why" of this PR is that we try to push the swap/push periodically the HDR outside of the app to either aggregate them or/and display them so that we don't loose it on deploy/crash
it's not optimal but it was useful ^^

with more background now than what i had ~1.5year ago i could workaround this by doing that fully in memory in a background service and then pulse it. but i would have to use an ArrayPool.Rent i guess to avoid allocation (this was probably one of the idea too)

**Comment by tebeco** [comment]
(and the issue was pointing  at a potential CTS when the app try to do a graceful shutdown)

**Comment by thefringeninja** [comment]
Oh sorry I'm not actually a maintainer :trollface: 

Pinging @LeeCampbell to take a look

**Comment by tebeco** [comment]
So it seems that i deleted my remote branch so i wont be able to to push new commit to it in this PR.
I could checkout the commit from this PR i guess to re-create it if it's mandatory but i guess Github would force me to close this one and re-open a new one.

Just tell me what you'd like me to do.

**Comment by tebeco** [comment]
> Oh sorry I'm not actually a maintainer :trollface:

image


i'm not sure i can follow what's going on here

**Comment by LeeCampbell** [comment]
Sorry for the massive delay on this.
Could I request that this PR is broken in to the parts it represents
 1. Update from .NET Core 1.1 to modern version of .Net Core
 2. Async
 3. Formatting and keyword usage updates

In general it looks good, but big PRs like that that represent multiple conceptual changes in my experience are ripe for introducing bugs

**Comment by tebeco** [comment]
splitting in smaller one is go ?
what order do you prefer ? any suggestion ?
will do it

**Comment by LeeCampbell** [comment]
I am not too worried about the order, but I think the order specified above makes sense.

**Comment by tebeco** [comment]
@LeeCampbell 
please check #72 #73 #74 #75 #76 #77

**Comment by thefringeninja** [comment]
I'm just as surprised as you are that I was able to click that...

**Comment by tebeco** [comment]
> I'm just as surprised as you are that I was able to click that...

What ??

**Comment by tebeco** [comment]
@LeeCampbell  @vgw-LeeCampbell

Should i close this PR now based on the others i created to split this one
Please check especially the first, as i did lots of small commits, and you might not want some of the commits inside

**Comment by LeeCampbell** [comment]
@tebeco what are your thoughts on becoming the maintainer on this repo?
I have put a lot of work into it, but on reflection I can not commit the time required to give it the attention it needs this year (or the last 2 years).

**Comment by tebeco** [comment]
i understand the issue here
and i'm truly sure that i do not have the technical requirements to fully understand the internal of the lib

maybe @onovotny could have idea about this

**Comment by tebeco** [comment]
@LeeCampbell 
so after few question around me to various people, if you think it can help you i can attempts to help as a "co-maintainer" as my knowledge would probably be the limit of probable PR going on
;)

So "why not", if you have question feel free to ask me about whatever you'd like before doing so

**Comment by tebeco** [comment]
@LeeCampbell 
if you are still interested/ looking for another maintainer
do not hesitate to contact me

probably from this or any open issue / PR
i would get a mail and it

**Comment by tebeco** [comment]
i understand the time is probably not adequate
but as i'm willing to help here

let me know if it's still up or not for you

**Comment by tebeco** [comment]
Closing
https://github.com/HdrHistogram/HdrHistogram.NET/pull/68#issuecomment-591661639

**Pull request closed without merging**
