### PR TITLE
.NET Standard

### PR DESCRIPTION
**Pull request by alhardy**
PR for https://github.com/HdrHistogram/HdrHistogram.NET/issues/17

### CODE REVIEW

**Comment by alhardy** [comment]
`nuget.exe` removed here https://github.com/HdrHistogram/HdrHistogram.NET/pull/51/commits/7cfe6332f6a7efb52758691e414ad0e774e5f956

and added to gitignore here https://github.com/HdrHistogram/HdrHistogram.NET/pull/51/commits/3f857771c8357d723ec780c2f5b2d7ba2df7ee50

**Comment by alhardy** [comment]
`default.ps1` is more of a `psake` convention, there is a `build.cmd` in the solution root which calls out to that.

**Comment by LeeCampbell** [comment]
Nice work @alhardy.
A few things need to get fixed before this gets merged.

Can we squish the commits. i.e. 
 * seems no point having the nuget.exe committed to the repo, then removed in the same PR.
 * I would rather the build scripts not know about AppVeyor, and have their SemVer passed in as an argument
 * merge commits instead of rebase

So it seems that there are 2 legitimate commits of the 7 in the PR. I can pick up this work and lean heavily on your good work if you are not up for it.

I will also need to change the AppVeyor builds as you have moved the build scripts, so this currently wont even build.

**Comment by alhardy** [comment]
@LeeCampbell yeah the appveyor build's broken due to the build changes I've made. 

I won't get a chance to make those changes for a couple of weeks, I've added you as a collaborator to my fork if you're happy to pick up the requested changes beforehand.

**Comment by ghuntley** [comment]
@leecampbell the tooling has changed so much you would be better off burning this PR to the ground. Happy to 1:1 and run you through how RxUI now does xtargeting/nuget creation. See ReactiveUI/ReactiveUI repo if you prefer self-service.

**Comment by LeeCampbell** [comment]
Thanks @alhardy finally closed by #58

**Pull request closed without merging**
